#!/usr/bin/env python3
"""
Generate Active Learning comparison diagram (Passive vs Active Learning).
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import os

# Output configuration
OUTPUT_DIR = "../figures"
OUTPUT_FILE = "active_learning_comparison.png"

# Color scheme
COLORS = {
    'data': '#e1f5ff',
    'selection': '#fff4e1',
    'labeling': '#ffe1f5',
    'model': '#e8f5e9',
}

def add_box(ax, x, y, width, height, text, color, fontsize=13):
    """Add a rounded box with text."""
    box = FancyBboxPatch((x, y), width, height,
                        boxstyle="round,pad=0.15",
                        facecolor=color,
                        edgecolor='black',
                        linewidth=2.5)
    ax.add_patch(box)
    ax.text(x + width/2, y + height/2, text, ha='center', va='center',
            fontsize=fontsize, fontweight='bold')

def add_arrow(ax, x1, y1, x2, y2, curved=False):
    """Add an arrow between boxes."""
    if curved:
        arrow = FancyArrowPatch((x1, y1), (x2, y2),
                              arrowstyle='->,head_width=0.5,head_length=0.7',
                              mutation_scale=25,
                              linewidth=2.5,
                              color='#666',
                              linestyle='dashed',
                              connectionstyle="arc3,rad=.3",
                              zorder=1)
    else:
        arrow = FancyArrowPatch((x1, y1), (x2, y2),
                              arrowstyle='->,head_width=0.5,head_length=0.7',
                              mutation_scale=25,
                              linewidth=2.5,
                              color='black',
                              zorder=2)
    ax.add_patch(arrow)

def create_diagram():
    fig, ax = plt.subplots(figsize=(14, 8), dpi=150)
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 8)
    ax.axis('off')

    # Title
    ax.text(7, 7.5, 'Passive vs Active Learning', fontsize=18, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='#e0e0e0', edgecolor='black', linewidth=2))

    # === PASSIVE LEARNING (Top) ===
    ax.text(7, 6.5, 'Passive Learning (Traditional)', fontsize=15, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#d0e0f0'))

    box_width = 2.5
    box_height = 1
    y_passive = 5

    # Random Data
    add_box(ax, 2, y_passive, box_width, box_height, 'Random\nData', COLORS['data'])

    # Label All
    add_box(ax, 5.5, y_passive, box_width, box_height, 'Label All', COLORS['selection'])

    # Train Model
    add_box(ax, 9, y_passive, box_width, box_height, 'Train\nModel', COLORS['model'])

    # Arrows
    add_arrow(ax, 4.5, y_passive + box_height/2, 5.5, y_passive + box_height/2)
    add_arrow(ax, 8, y_passive + box_height/2, 9, y_passive + box_height/2)

    # Annotation
    ax.text(7, 4.2, 'Simple but expensive: label everything', fontsize=11, ha='center', style='italic',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='#ffffcc'))

    # === ACTIVE LEARNING (Bottom) ===
    ax.text(7, 3.5, 'Active Learning', fontsize=15, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#f0e0d0'))

    y_active = 1.8

    # Unlabeled Pool
    add_box(ax, 1, y_active, box_width, box_height, 'Unlabeled\nPool', COLORS['data'])

    # Select Most Informative
    add_box(ax, 4, y_active, box_width, box_height, 'Select Most\nInformative', COLORS['selection'])

    # Oracle Labels
    add_box(ax, 7, y_active, box_width, box_height, 'Oracle\nLabels', COLORS['labeling'])

    # Train Model
    add_box(ax, 10, y_active, box_width, box_height, 'Train\nModel', COLORS['model'])

    # Forward arrows
    add_arrow(ax, 3.5, y_active + box_height/2, 4, y_active + box_height/2)
    add_arrow(ax, 6.5, y_active + box_height/2, 7, y_active + box_height/2)
    add_arrow(ax, 9.5, y_active + box_height/2, 10, y_active + box_height/2)

    # Feedback loop (curved arrow from Train Model back to Select)
    add_arrow(ax, 11.25, y_active + 0.2, 5.25, y_active + 0.2, curved=True)

    # Loop label
    ax.text(8.2, 0.9, 'Iterative refinement', fontsize=10, ha='center', style='italic', color='#666')

    # Annotation
    ax.text(7, 0.5, 'Efficient: intelligently choose what to label', fontsize=11, ha='center', style='italic',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='#ccffcc'))

    # Key difference highlight
    ax.text(7, -0.2, 'Key difference: Active learner chooses what to learn from', fontsize=12, ha='center',
            fontweight='bold', bbox=dict(boxstyle='round,pad=0.4', facecolor='#ffe0e0', linewidth=2))

    # Source attribution
    ax.text(0.5, 0.02, 'Generated by: diagram-generators/active_learning_comparison.py',
            fontsize=9, style='italic', color='#666', transform=ax.transAxes)

    # Save
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"✓ Generated: {output_path}")

if __name__ == "__main__":
    create_diagram()
