"""
Generate Fast-Forward Merge diagram
Shows: Before and after fast-forward merge
"""

import matplotlib.pyplot as plt
from matplotlib.patches import Circle, FancyBboxPatch, FancyArrowPatch
import os

OUTPUT_DIR = "../figures"
os.makedirs(OUTPUT_DIR, exist_ok=True)

COLORS = {
    'commit': '#e1f5ff',
    'main': '#e8f5e9',
    'feature': '#fff4e1',
}

def create_diagram():
    fig, ax = plt.subplots(figsize=(14, 10), dpi=150)
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 10)
    ax.axis('off')

    def add_commit(x, y, label, color=COLORS['commit']):
        circle = Circle((x, y), 0.5, facecolor=color,
                       edgecolor='black', linewidth=2.5, zorder=3)
        ax.add_patch(circle)
        ax.text(x, y, label, ha='center', va='center',
                fontsize=13, fontweight='bold', zorder=4)

    def add_branch_label(x, y, text, color):
        box = FancyBboxPatch((x - 0.7, y - 0.35), 1.4, 0.7,
                            boxstyle="round,pad=0.1",
                            facecolor=color,
                            edgecolor='black',
                            linewidth=2.5)
        ax.add_patch(box)
        ax.text(x, y, text, ha='center', va='center',
                fontsize=12, fontweight='bold')

    def add_arrow_between_commits(x1, y1, x2, y2):
        arrow = FancyArrowPatch((x1 - 0.5, y1), (x2 + 0.5, y2),
                               arrowstyle='<-,head_width=0.5,head_length=0.5',
                               color='#666',
                               linewidth=2,
                               mutation_scale=20,
                               zorder=2)
        ax.add_patch(arrow)

    # BEFORE MERGE (top section)
    ax.text(7, 9.2, 'Before Merge', fontsize=18, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#e0e0e0',
                     edgecolor='black', linewidth=2))

    # Commits
    commits_before = [(2.5, 7, 'C1'), (5, 7, 'C2'), (7.5, 7, 'C3'), (10, 7, 'C4')]
    for i, (x, y, label) in enumerate(commits_before):
        add_commit(x, y, label)
        if i > 0:
            add_arrow_between_commits(x, y, commits_before[i-1][0], commits_before[i-1][1])

    # Branch labels
    add_branch_label(2.5, 8.2, 'main', COLORS['main'])
    add_branch_label(10, 8.2, 'feature', COLORS['feature'])

    # Arrows from labels to commits
    for x, label_y, commit_y in [(2.5, 7.85, 7.5), (10, 7.85, 7.5)]:
        arrow = FancyArrowPatch((x, label_y), (x, commit_y),
                               arrowstyle='->,head_width=0.5,head_length=0.4',
                               color='black', linewidth=2, mutation_scale=20)
        ax.add_patch(arrow)

    # AFTER MERGE (bottom section)
    ax.text(7, 4.8, 'After: git merge feature', fontsize=18, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#c8e6c9',
                     edgecolor='black', linewidth=2))

    # Commits (same positions)
    commits_after = [(2.5, 2.5, 'C1'), (5, 2.5, 'C2'), (7.5, 2.5, 'C3'), (10, 2.5, 'C4')]
    for i, (x, y, label) in enumerate(commits_after):
        add_commit(x, y, label)
        if i > 0:
            add_arrow_between_commits(x, y, commits_after[i-1][0], commits_after[i-1][1])

    # Only main label now (at C4)
    add_branch_label(10, 3.7, 'main', COLORS['main'])
    arrow = FancyArrowPatch((10, 3.35), (10, 3.0),
                           arrowstyle='->,head_width=0.5,head_length=0.4',
                           color='black', linewidth=2, mutation_scale=20)
    ax.add_patch(arrow)

    # Result explanation
    ax.text(7, 0.8,
            'Result: main pointer moved forward to C4\nNo merge commit needed (linear history preserved)',
            ha='center', fontsize=12, style='italic',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#ffffcc',
                     edgecolor='black', linewidth=1.5))

    plt.title('Fast-Forward Merge', fontsize=20, fontweight='bold', pad=15)

    # Source attribution
    ax.text(0.5, 0.2, 'Generated by: diagram-generators/git_fast_forward_merge.py',
            fontsize=9, style='italic', color='#666')

    plt.tight_layout()
    output_path = f'{OUTPUT_DIR}/git_fast_forward_merge.png'
    plt.savefig(output_path, bbox_inches='tight', dpi=150, facecolor='white')
    plt.close()

    return output_path

if __name__ == "__main__":
    output = create_diagram()
    print(f"✓ Generated: {output}")
