#!/usr/bin/env python3
"""
Generate Git Fetch vs Pull comparison diagram.
"""

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle
import os

OUTPUT_DIR = "../figures"
OUTPUT_FILE = "git_fetch_vs_pull.png"

COLORS = {
    'fetch_unchanged': '#fff4e1',
    'pull_updated': '#e8f5e9',
}

def add_box(ax, x, y, width, height, text, color, fontsize=13):
    """Add a rounded box with text."""
    box = FancyBboxPatch((x, y), width, height,
                        boxstyle="round,pad=0.15",
                        facecolor=color,
                        edgecolor='black',
                        linewidth=2.5)
    ax.add_patch(box)
    ax.text(x + width/2, y + height/2, text, ha='center', va='center',
            fontsize=fontsize, fontweight='bold')

def add_arrow(ax, x1, y1, x2, y2):
    """Add an arrow."""
    arrow = FancyArrowPatch((x1, y1), (x2, y2),
                          arrowstyle='->',
                          mutation_scale=25,
                          linewidth=2.5,
                          color='black',
                          zorder=2)
    ax.add_patch(arrow)

def create_diagram():
    fig, ax = plt.subplots(figsize=(16, 8), dpi=200)
    ax.set_xlim(0, 16)
    ax.set_ylim(0, 8)
    ax.axis('off')

    # Title
    ax.text(8, 7.3, 'git fetch vs git pull', fontsize=20, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#e0e0e0', edgecolor='black', linewidth=2))

    # === LEFT: git fetch ===
    # Background
    fetch_bg = Rectangle((0.5, 3), 7, 3.5, facecolor='#f0f8ff', edgecolor='#0066cc',
                         linewidth=3, linestyle='--', alpha=0.3, zorder=0)
    ax.add_patch(fetch_bg)

    ax.text(4, 6.2, 'git fetch', fontsize=17, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#d0e0f0'))

    # origin/main box
    add_box(ax, 1.5, 5, 5, 0.8, 'origin/main: C5', '#e1f5ff')

    # Arrow pointing to local main
    add_arrow(ax, 4, 5, 4, 4.2)

    # local main box (unchanged)
    add_box(ax, 1.5, 3.4, 5, 0.8, 'local main: C3', COLORS['fetch_unchanged'])

    # Explanation
    ax.text(4, 2.5, 'Downloads commits\nLocal branch unchanged\nReview before merging',
            fontsize=11, ha='center', style='italic',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#ffffcc'))

    # === RIGHT: git pull ===
    # Background
    pull_bg = Rectangle((8.5, 3), 7, 3.5, facecolor='#f0fff0', edgecolor='#00cc66',
                        linewidth=3, linestyle='--', alpha=0.3, zorder=0)
    ax.add_patch(pull_bg)

    ax.text(12, 6.2, 'git pull', fontsize=17, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#d0f0d0'))

    # origin/main box
    add_box(ax, 9.5, 5, 5, 0.8, 'origin/main: C5', '#e1f5ff')

    # Arrow pointing to local main
    add_arrow(ax, 12, 5, 12, 4.2)

    # local main box (updated!)
    add_box(ax, 9.5, 3.4, 5, 0.8, 'local main: C5', COLORS['pull_updated'])

    # Explanation
    ax.text(12, 2.5, 'Downloads + merges\nLocal branch updated\nImmediate integration',
            fontsize=11, ha='center', style='italic',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#ccffcc'))

    # Bottom comparison
    ax.text(4, 1.5, 'fetch = download only', fontsize=13, ha='center', fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#fff4e1', linewidth=2))

    ax.text(12, 1.5, 'pull = fetch + merge', fontsize=13, ha='center', fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#e8f5e9', linewidth=2))

    # Best practice note
    ax.text(8, 0.5, 'Best Practice: Use git fetch to review changes, then merge manually',
            fontsize=13, ha='center', style='italic',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='#ffe0e0', linewidth=2.5))

    # Source attribution
    ax.text(0.5, 0.02, 'Generated by: diagram-generators/git_fetch_vs_pull.py',
            fontsize=9, style='italic', color='#666', transform=ax.transAxes)

    # Save
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=200, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"✓ Generated: {output_path}")

if __name__ == "__main__":
    create_diagram()
