#!/usr/bin/env python3
"""
Generate Git Conflict Resolution sequence diagram.
"""

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle
import os

OUTPUT_DIR = "../figures"
OUTPUT_FILE = "git_conflict_resolution.png"

def add_box(ax, x, y, width, height, text, color='#e0e0e0', fontsize=12):
    """Add a box."""
    box = FancyBboxPatch((x, y), width, height,
                        boxstyle="round,pad=0.1",
                        facecolor=color,
                        edgecolor='black',
                        linewidth=2.5)
    ax.add_patch(box)
    ax.text(x + width/2, y + height/2, text, ha='center', va='center',
            fontsize=fontsize, fontweight='bold')

def add_arrow(ax, x1, y1, x2, y2, label='', style='solid'):
    """Add an arrow with label."""
    arrow = FancyArrowPatch((x1, y1), (x2, y2),
                          arrowstyle='->',
                          mutation_scale=20,
                          linewidth=2,
                          color='black',
                          linestyle=style,
                          zorder=2)
    ax.add_patch(arrow)
    if label:
        mid_x = (x1 + x2) / 2
        ax.text(mid_x + 0.3, y1, label, fontsize=10, ha='left',
                bbox=dict(boxstyle='round,pad=0.2', facecolor='white', alpha=0.9))

def draw_lifeline(ax, x, y_start, y_end):
    """Draw a vertical lifeline."""
    ax.plot([x, x], [y_start, y_end], 'k--', linewidth=2, alpha=0.5)

def create_diagram():
    fig, ax = plt.subplots(figsize=(16, 11), dpi=200)
    ax.set_xlim(0, 16)
    ax.set_ylim(0, 11)
    ax.axis('off')

    # Title
    ax.text(8, 10.3, 'Git Merge Conflict Resolution Process', fontsize=20, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#e0e0e0', edgecolor='black', linewidth=2))

    # Participants
    add_box(ax, 1.5, 9, 2.5, 0.7, 'User', '#e1f5ff', 13)
    add_box(ax, 6.5, 9, 2.5, 0.7, 'Git', '#fff4e1', 13)
    add_box(ax, 11.5, 9, 2.5, 0.7, 'File', '#ffe1f5', 13)

    # Lifelines
    draw_lifeline(ax, 2.75, 9, 0.8)
    draw_lifeline(ax, 7.75, 9, 0.8)
    draw_lifeline(ax, 12.75, 9, 0.8)

    y = 8.5

    # Step 1: git merge
    add_arrow(ax, 2.75, y, 7.75, y, 'git merge feature')
    y -= 0.6

    # Step 2: Git checks file
    add_arrow(ax, 7.75, y, 12.75, y, 'Check for conflicts')
    y -= 0.6

    # Step 3: Conflict detected
    add_arrow(ax, 12.75, y, 7.75, y, 'Conflict!', 'dashed')
    y -= 0.6

    # Step 4: Git reports to user
    add_arrow(ax, 7.75, y, 2.75, y, 'CONFLICT in main.py', 'dashed')
    y -= 0.7

    # Conflict box
    conflict_box = Rectangle((1, y - 0.4), 3.5, 0.8, facecolor='#ffcccc', edgecolor='#cc0000',
                             linewidth=2.5, zorder=1)
    ax.add_patch(conflict_box)
    ax.text(2.75, y, '⚠ Merge stopped\nConflict markers added',
            fontsize=11, ha='center', va='center', fontweight='bold')
    y -= 1

    # Step 5: User edits file
    add_arrow(ax, 2.75, y, 12.75, y, 'Edit file, remove markers')
    y -= 0.6

    # Step 6: File returns resolved version
    add_arrow(ax, 12.75, y, 2.75, y, 'Resolved version', 'dashed')
    y -= 0.7

    # Resolution box
    resolution_box = Rectangle((1, y - 0.4), 3.5, 0.8, facecolor='#ccffcc', edgecolor='#00cc00',
                               linewidth=2.5, zorder=1)
    ax.add_patch(resolution_box)
    ax.text(2.75, y, '✓ Conflict resolved\nReady to stage',
            fontsize=11, ha='center', va='center', fontweight='bold')
    y -= 1

    # Step 7: git add
    add_arrow(ax, 2.75, y, 7.75, y, 'git add main.py')
    y -= 0.6

    # Step 8: git commit
    add_arrow(ax, 2.75, y, 7.75, y, 'git commit -m "Resolve"')
    y -= 0.6

    # Step 9: Complete
    add_arrow(ax, 7.75, y, 2.75, y, 'Merge complete!', 'dashed')
    y -= 0.8

    # Final note
    note_box = Rectangle((5.5, y - 0.5), 5, 0.8, facecolor='#e0f0ff', edgecolor='#0066cc',
                         linewidth=2, linestyle='--', zorder=1)
    ax.add_patch(note_box)
    ax.text(8, y - 0.1, 'Creates merge commit\nwith two parents',
            fontsize=11, ha='center', va='center', style='italic', fontweight='bold')

    # Source attribution
    ax.text(0.5, 0.02, 'Generated by: diagram-generators/git_conflict_resolution.py',
            fontsize=9, style='italic', color='#666', transform=ax.transAxes)

    # Save
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=200, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"✓ Generated: {output_path}")

if __name__ == "__main__":
    create_diagram()
