"""
Generate Branch as Pointer diagram
Shows: HEAD -> branch -> commit relationship
"""

import matplotlib.pyplot as plt
from matplotlib.patches import Circle, FancyBboxPatch, FancyArrowPatch
import os

OUTPUT_DIR = "../figures"
os.makedirs(OUTPUT_DIR, exist_ok=True)

COLORS = {
    'commit': '#e1f5ff',
    'branch': '#e8f5e9',
    'head': '#ffe1f5',
}

def create_diagram():
    fig, ax = plt.subplots(figsize=(14, 8), dpi=150)
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 8)
    ax.axis('off')

    # Commits (bottom)
    commits = [(3, 2.5, 'C1'), (6.5, 2.5, 'C2'), (10, 2.5, 'C3')]

    for x, y, label in commits:
        circle = Circle((x, y), 0.55, facecolor=COLORS['commit'],
                       edgecolor='black', linewidth=3, zorder=3)
        ax.add_patch(circle)
        ax.text(x, y, label, ha='center', va='center',
                fontsize=14, fontweight='bold', zorder=4)

    # Arrows between commits (pointing backwards)
    arrow1 = FancyArrowPatch((6.5 - 0.6, 2.5), (3 + 0.6, 2.5),
                            arrowstyle='<-,head_width=0.6,head_length=0.6',
                            color='#666',
                            linewidth=2.5,
                            mutation_scale=25,
                            zorder=2)
    ax.add_patch(arrow1)

    arrow2 = FancyArrowPatch((10 - 0.6, 2.5), (6.5 + 0.6, 2.5),
                            arrowstyle='<-,head_width=0.6,head_length=0.6',
                            color='#666',
                            linewidth=2.5,
                            mutation_scale=25,
                            zorder=2)
    ax.add_patch(arrow2)

    # Branch pointer
    branch_box = FancyBboxPatch((9, 4.8), 2, 0.8,
                               boxstyle="round,pad=0.15",
                               facecolor=COLORS['branch'],
                               edgecolor='black',
                               linewidth=3)
    ax.add_patch(branch_box)
    ax.text(10, 5.2, 'main',
            ha='center', va='center',
            fontsize=16, fontweight='bold')

    # Arrow from branch to commit
    arrow_branch = FancyArrowPatch((10, 4.8), (10, 3.05),
                                  arrowstyle='->,head_width=0.7,head_length=0.7',
                                  color='black',
                                  linewidth=3,
                                  mutation_scale=30)
    ax.add_patch(arrow_branch)
    ax.text(10.7, 3.9, 'points to',
            fontsize=11, style='italic')

    # HEAD pointer
    head_box = FancyBboxPatch((5.5, 6.5), 2.5, 0.8,
                             boxstyle="round,pad=0.15",
                             facecolor=COLORS['head'],
                             edgecolor='black',
                             linewidth=3)
    ax.add_patch(head_box)
    ax.text(6.75, 6.9, 'HEAD',
            ha='center', va='center',
            fontsize=16, fontweight='bold')

    # Arrow from HEAD to branch
    arrow_head = FancyArrowPatch((7.5, 6.7), (9, 5.4),
                                arrowstyle='->,head_width=0.7,head_length=0.7',
                                color='black',
                                linewidth=3,
                                mutation_scale=30)
    ax.add_patch(arrow_head)
    ax.text(8.5, 6.3, 'points to',
            fontsize=11, style='italic')

    plt.title('Branch as a Pointer to a Commit',
             fontsize=20, fontweight='bold', pad=15)

    # Add explanatory text
    ax.text(7, 0.8, 'A branch is just a lightweight movable pointer to a commit',
            ha='center', fontsize=12, style='italic',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#ffffcc',
                     edgecolor='black', linewidth=1.5))

    # Source attribution
    ax.text(0.5, 0.2, 'Generated by: diagram-generators/git_branch_pointer.py',
            fontsize=9, style='italic', color='#666')

    plt.tight_layout()
    output_path = f'{OUTPUT_DIR}/git_branch_pointer.png'
    plt.savefig(output_path, bbox_inches='tight', dpi=150, facecolor='white')
    plt.close()

    return output_path

if __name__ == "__main__":
    output = create_diagram()
    print(f"✓ Generated: {output}")
