"""
Generate Git Three States diagram
Shows: Working Directory -> Staging Area -> Repository
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import os

# Output configuration
OUTPUT_DIR = "../figures"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Color scheme matching slides
COLORS = {
    'input': '#e1f5ff',
    'processing': '#fff4e1',
    'output': '#e8f5e9',
}

def create_diagram():
    fig, ax = plt.subplots(figsize=(14, 6), dpi=150)
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 6)
    ax.axis('off')

    # Box dimensions
    box_width = 3.5
    box_height = 2
    y_pos = 2

    # Working Directory
    box1 = FancyBboxPatch((1, y_pos), box_width, box_height,
                          boxstyle="round,pad=0.15",
                          facecolor=COLORS['input'],
                          edgecolor='black',
                          linewidth=3)
    ax.add_patch(box1)
    ax.text(2.75, y_pos + 1, 'Working\nDirectory',
            ha='center', va='center',
            fontsize=16, fontweight='bold')

    # Staging Area
    box2 = FancyBboxPatch((5.25, y_pos), box_width, box_height,
                          boxstyle="round,pad=0.15",
                          facecolor=COLORS['processing'],
                          edgecolor='black',
                          linewidth=3)
    ax.add_patch(box2)
    ax.text(7, y_pos + 1, 'Staging Area\n(Index)',
            ha='center', va='center',
            fontsize=16, fontweight='bold')

    # Repository
    box3 = FancyBboxPatch((9.5, y_pos), box_width, box_height,
                          boxstyle="round,pad=0.15",
                          facecolor=COLORS['output'],
                          edgecolor='black',
                          linewidth=3)
    ax.add_patch(box3)
    ax.text(11.25, y_pos + 1, 'Repository\n(.git)',
            ha='center', va='center',
            fontsize=16, fontweight='bold')

    # Forward arrows
    arrow1 = FancyArrowPatch((4.5, y_pos + 1.3), (5.25, y_pos + 1.3),
                            arrowstyle='->,head_width=0.8,head_length=0.8',
                            color='black',
                            linewidth=3,
                            mutation_scale=30)
    ax.add_patch(arrow1)
    ax.text(4.875, y_pos + 1.8, 'git add',
            ha='center', fontsize=13, fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='white',
                     edgecolor='black', linewidth=2))

    arrow2 = FancyArrowPatch((8.75, y_pos + 1.3), (9.5, y_pos + 1.3),
                            arrowstyle='->,head_width=0.8,head_length=0.8',
                            color='black',
                            linewidth=3,
                            mutation_scale=30)
    ax.add_patch(arrow2)
    ax.text(9.125, y_pos + 1.8, 'git commit',
            ha='center', fontsize=13, fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='white',
                     edgecolor='black', linewidth=2))

    # Backward arrow
    arrow3 = FancyArrowPatch((9.5, y_pos + 0.7), (4.5, y_pos + 0.7),
                            arrowstyle='<-,head_width=0.8,head_length=0.8',
                            color='#666',
                            linewidth=2.5,
                            mutation_scale=30,
                            linestyle='--')
    ax.add_patch(arrow3)
    ax.text(7, y_pos + 0.2, 'git checkout',
            ha='center', fontsize=12, style='italic',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='white',
                     edgecolor='#666', linewidth=1.5))

    plt.title('Git: The Three States', fontsize=20, fontweight='bold', pad=15)

    # Add source attribution
    ax.text(0.5, 0.3, 'Generated by: diagram-generators/git_three_states.py',
            fontsize=9, style='italic', color='#666')

    plt.tight_layout()
    output_path = f'{OUTPUT_DIR}/git_three_states.png'
    plt.savefig(output_path, bbox_inches='tight', dpi=150, facecolor='white')
    plt.close()

    return output_path

if __name__ == "__main__":
    output = create_diagram()
    print(f"✓ Generated: {output}")
