"""
Generate Local vs Remote diagram
Shows: Working Directory -> Staging -> Local Repo <-> Remote Repo
"""

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle
import os

OUTPUT_DIR = "../figures"
os.makedirs(OUTPUT_DIR, exist_ok=True)

COLORS = {
    'input': '#e1f5ff',
    'processing': '#fff4e1',
    'output': '#e8f5e9',
    'remote': '#ffe1f5',
}

def create_diagram():
    fig, ax = plt.subplots(figsize=(14, 10), dpi=150)
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 10)
    ax.axis('off')

    # Helper function
    def add_box(x, y, width, height, text, color, fontsize=13):
        box = FancyBboxPatch((x, y), width, height,
                            boxstyle="round,pad=0.12",
                            facecolor=color,
                            edgecolor='black',
                            linewidth=2.5)
        ax.add_patch(box)
        ax.text(x + width/2, y + height/2, text,
                ha='center', va='center',
                fontsize=fontsize, fontweight='bold')

    def add_arrow(x1, y1, x2, y2, label='', style='->'):
        arrow = FancyArrowPatch((x1, y1), (x2, y2),
                               arrowstyle=f'{style},head_width=0.7,head_length=0.7',
                               color='black',
                               linewidth=2.5,
                               mutation_scale=28)
        ax.add_patch(arrow)
        if label:
            mid_x, mid_y = (x1 + x2) / 2, (y1 + y2) / 2
            ax.text(mid_x, mid_y + 0.3, label,
                   ha='center', fontsize=12, fontweight='bold',
                   bbox=dict(boxstyle='round,pad=0.4', facecolor='white',
                            edgecolor='black', linewidth=2))

    # Local section background
    local_bg = Rectangle((0.3, 2), 6, 6.5,
                         facecolor='#f8f8f8',
                         edgecolor='#666',
                         linewidth=2,
                         linestyle='--',
                         alpha=0.3)
    ax.add_patch(local_bg)
    ax.text(3.3, 8.3, 'Your Computer (Local)',
            fontsize=16, fontweight='bold', ha='center')

    # Remote section background
    remote_bg = Rectangle((7.7, 4), 5.8, 3.5,
                          facecolor='#f0f0ff',
                          edgecolor='#666',
                          linewidth=2,
                          linestyle='--',
                          alpha=0.3)
    ax.add_patch(remote_bg)
    ax.text(10.6, 7.3, 'GitHub/GitLab (Remote)',
            fontsize=16, fontweight='bold', ha='center')

    # Local boxes
    add_box(1, 6.5, 2.2, 1, 'Working\nDirectory', COLORS['input'], 13)
    add_box(1, 4.8, 2.2, 1, 'Staging\nArea', COLORS['processing'], 13)
    add_box(1, 3.1, 2.2, 1, 'Local\nRepository', COLORS['output'], 13)

    # Remote box
    add_box(8.5, 5, 4, 1.5, 'Remote\nRepository', COLORS['remote'], 15)

    # Local arrows (vertical)
    add_arrow(2.1, 6.5, 2.1, 5.8, 'git add')
    add_arrow(2.1, 4.8, 2.1, 4.1, 'git commit')
    add_arrow(2.1, 3.1, 2.1, 5.6, 'git checkout', '<-')

    # Remote arrows (horizontal)
    add_arrow(3.2, 3.6, 8.5, 5.4, 'git push')
    add_arrow(8.5, 6.1, 3.2, 3.9, 'git pull', '<-')

    plt.title('Local vs Remote Repositories',
             fontsize=20, fontweight='bold', pad=15)

    # Add note
    ax.text(7, 1.5,
            'git push: Upload local changes to remote\ngit pull: Download and merge remote changes',
            ha='center', fontsize=11, style='italic',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#ffffcc',
                     edgecolor='black', linewidth=1.5))

    # Source attribution
    ax.text(0.5, 0.5, 'Generated by: diagram-generators/git_local_remote.py',
            fontsize=9, style='italic', color='#666')

    plt.tight_layout()
    output_path = f'{OUTPUT_DIR}/git_local_remote.png'
    plt.savefig(output_path, bbox_inches='tight', dpi=150, facecolor='white')
    plt.close()

    return output_path

if __name__ == "__main__":
    output = create_diagram()
    print(f"✓ Generated: {output}")
