#!/usr/bin/env python3
"""Generate Git Push visualization."""
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle
import os

OUTPUT_DIR, OUTPUT_FILE = "../figures", "git_push_visualization.png"
COLORS = {'remote': '#ffe1f5', 'local': '#e8f5e9', 'commit': '#e1f5ff'}

def add_box(ax, x, y, w, h, text, color, fs=12):
    box = FancyBboxPatch((x,y), w, h, boxstyle="round,pad=0.1", facecolor=color, edgecolor='black', linewidth=2.5)
    ax.add_patch(box)
    ax.text(x+w/2, y+h/2, text, ha='center', va='center', fontsize=fs, fontweight='bold')

def add_arrow(ax, x1, y1, x2, y2, style='solid'):
    arrow = FancyArrowPatch((x1,y1), (x2,y2), arrowstyle='->', mutation_scale=25, linewidth=2.5, color='black', linestyle=style, zorder=2)
    ax.add_patch(arrow)

def create_diagram():
    fig, ax = plt.subplots(figsize=(16, 9), dpi=200)
    ax.set_xlim(0, 16); ax.set_ylim(0, 9); ax.axis('off')
    
    ax.text(8, 8.5, 'After: git push origin main', fontsize=20, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#e0e0e0', edgecolor='black', linewidth=2))
    
    # Remote section
    remote_bg = Rectangle((1, 5.5), 6, 2.3, facecolor='#fff0f5', edgecolor='#cc0066', linewidth=3, linestyle='--', alpha=0.3)
    ax.add_patch(remote_bg)
    ax.text(4, 7.5, 'Remote (GitHub)', fontsize=15, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='#ffd0e0'))
    
    add_box(ax, 2, 6, 4, 0.8, 'origin/main', COLORS['remote'], 13)
    add_arrow(ax, 5.5, 6.4, 8, 6.4, 'dashed')
    add_box(ax, 8.5, 6, 2, 0.8, 'C3', COLORS['commit'])
    add_arrow(ax, 10, 6.4, 11.5, 6.4)
    add_box(ax, 12, 6, 2, 0.8, 'C2', COLORS['commit'])
    
    # Local section  
    local_bg = Rectangle((1, 2), 6, 2.3, facecolor='#f0fff0', edgecolor='#00cc66', linewidth=3, linestyle='--', alpha=0.3)
    ax.add_patch(local_bg)
    ax.text(4, 4, 'Local', fontsize=15, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='#d0f0d0'))
    
    add_box(ax, 2, 2.5, 4, 0.8, 'main', COLORS['local'], 13)
    add_arrow(ax, 5.5, 2.9, 8, 2.9, 'dashed')
    add_box(ax, 8.5, 2.5, 2, 0.8, 'C3', COLORS['commit'])
    add_arrow(ax, 10, 2.9, 11.5, 2.9)
    add_box(ax, 12, 2.5, 2, 0.8, 'C2', COLORS['commit'])
    
    # Push arrow
    ax.annotate('', xy=(4, 5.5), xytext=(4, 4.3), arrowprops=dict(arrowstyle='->', lw=4, color='#0066cc'))
    ax.text(4.5, 4.9, 'git push', fontsize=14, fontweight='bold', bbox=dict(boxstyle='round,pad=0.3', facecolor='#d0e0ff'))
    
    ax.text(8, 1, 'Both local and remote at same commit after push', fontsize=13, ha='center', style='italic',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='#ffffcc', linewidth=2))
    
    ax.text(0.5, 0.02, 'Generated by: diagram-generators/git_push_visualization.py', fontsize=9, style='italic', color='#666', transform=ax.transAxes)
    
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=200, bbox_inches='tight', facecolor='white')
    plt.close()
    print(f"✓ Generated: {output_path}")

if __name__ == "__main__":
    create_diagram()
