"""
Generate Commit History DAG diagram
Shows: Linear commit history with arrows pointing backwards
"""

import matplotlib.pyplot as plt
from matplotlib.patches import Circle, FancyArrowPatch
import os

OUTPUT_DIR = "../figures"
os.makedirs(OUTPUT_DIR, exist_ok=True)

COLORS = {
    'commit': '#e8f5e9',
}

def create_diagram():
    fig, ax = plt.subplots(figsize=(14, 6), dpi=150)
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 6)
    ax.axis('off')

    # Commit positions
    commits = [
        (2.5, 3.5, 'C0', 'Initial\ncommit'),
        (5, 3.5, 'C1', 'Add user\nmodel'),
        (7.5, 3.5, 'C2', 'Add\nvalidation'),
        (10, 3.5, 'C3', 'Fix bug'),
        (12.5, 3.5, 'C4', 'Add tests'),
    ]

    # Draw commits
    for x, y, label, desc in commits:
        circle = Circle((x, y), 0.5, facecolor=COLORS['commit'],
                       edgecolor='black', linewidth=3, zorder=3)
        ax.add_patch(circle)
        ax.text(x, y, label, ha='center', va='center',
                fontsize=14, fontweight='bold', zorder=4)
        ax.text(x, y - 1.2, desc, ha='center', va='top',
                fontsize=11, style='italic')

    # Draw arrows (pointing backwards - history flows backwards)
    for i in range(len(commits) - 1):
        x1, y1 = commits[i+1][0], commits[i+1][1]
        x2, y2 = commits[i][0], commits[i][1]

        # Arrow from newer to older commit
        arrow = FancyArrowPatch((x1 - 0.5, y1), (x2 + 0.5, y2),
                               arrowstyle='->,head_width=0.6,head_length=0.6',
                               color='black',
                               linewidth=2.5,
                               mutation_scale=25,
                               zorder=2)
        ax.add_patch(arrow)

    plt.title('Commit History as Directed Acyclic Graph (DAG)',
             fontsize=20, fontweight='bold', pad=15)

    # Add note
    ax.text(7, 5.2, 'Each commit points to its parent (history flows backwards)',
            ha='center', fontsize=12, style='italic',
            bbox=dict(boxstyle='round,pad=0.7', facecolor='#ffffcc',
                     edgecolor='black', linewidth=1.5))

    # Source attribution
    ax.text(0.5, 0.3, 'Generated by: diagram-generators/git_commit_dag.py',
            fontsize=9, style='italic', color='#666')

    plt.tight_layout()
    output_path = f'{OUTPUT_DIR}/git_commit_dag.png'
    plt.savefig(output_path, bbox_inches='tight', dpi=150, facecolor='white')
    plt.close()

    return output_path

if __name__ == "__main__":
    output = create_diagram()
    print(f"✓ Generated: {output}")
