#!/usr/bin/env python3
"""
Generate Git Three-Way Merge diagram showing before and after merge states.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Circle
import os

# Output configuration
OUTPUT_DIR = "../figures"
OUTPUT_FILE = "git_three_way_merge.png"

# Color scheme
COLORS = {
    'branch_main': '#fff4e1',
    'branch_feature': '#e8f5e9',
    'commit': '#e1f5ff',
    'common_ancestor': '#ffe1f5',
    'merge_commit': '#c8e6c9',
    'head': '#ffe1f5',
}

def add_commit_node(ax, x, y, label, color, size=0.8):
    """Add a commit node (circle)."""
    circle = Circle((x, y), size, facecolor=color, edgecolor='black', linewidth=2.5, zorder=3)
    ax.add_patch(circle)
    ax.text(x, y, label, ha='center', va='center', fontsize=12, fontweight='bold', zorder=4)

def add_branch_label(ax, x, y, label, color):
    """Add a branch label box."""
    box = FancyBboxPatch((x - 0.8, y - 0.35), 1.6, 0.7,
                        boxstyle="round,pad=0.1",
                        facecolor=color,
                        edgecolor='black',
                        linewidth=2.5,
                        zorder=5)
    ax.add_patch(box)
    ax.text(x, y, label, ha='center', va='center', fontsize=13, fontweight='bold', zorder=6)

def add_arrow(ax, x1, y1, x2, y2, style='solid', color='black'):
    """Add an arrow between commits."""
    arrow = FancyArrowPatch((x1, y1), (x2, y2),
                          arrowstyle='->',
                          mutation_scale=30,
                          linewidth=2.5,
                          color=color,
                          linestyle=style,
                          zorder=2)
    ax.add_patch(arrow)

def create_diagram():
    fig, ax = plt.subplots(figsize=(14, 10), dpi=150)
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 10)
    ax.axis('off')

    # Title sections
    ax.text(7, 9.2, 'Before Merge', fontsize=18, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#e0e0e0', edgecolor='black', linewidth=2))

    # BEFORE MERGE (top section, y=5.5-8.5)
    # Commits
    add_commit_node(ax, 3, 7, 'C1', COLORS['commit'])
    add_commit_node(ax, 6, 7, 'C2\ncommon\nancestor', COLORS['common_ancestor'], size=1.0)
    add_commit_node(ax, 9, 8.2, 'C3\nmain work', COLORS['commit'], size=0.9)
    add_commit_node(ax, 9, 5.8, 'C4\nfeature\nwork', COLORS['commit'], size=0.9)

    # Arrows (commits point backwards)
    add_arrow(ax, 5.2, 7, 3.8, 7)  # C2 -> C1
    add_arrow(ax, 8.2, 8.1, 6.8, 7.2)  # C3 -> C2
    add_arrow(ax, 8.2, 5.9, 6.8, 6.8)  # C4 -> C2

    # Branch labels
    add_branch_label(ax, 11.5, 8.2, 'main', COLORS['branch_main'])
    add_branch_label(ax, 11.5, 5.8, 'feature', COLORS['branch_feature'])

    # Dashed arrows from branches to commits
    add_arrow(ax, 10.7, 8.2, 9.8, 8.2, style='dashed', color='gray')
    add_arrow(ax, 10.7, 5.8, 9.8, 5.8, style='dashed', color='gray')

    # Divider line
    ax.plot([0.5, 13.5], [4.8, 4.8], 'k-', linewidth=2, alpha=0.5)

    # AFTER MERGE section title
    ax.text(7, 4, 'After: git merge feature', fontsize=18, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#e0e0e0', edgecolor='black', linewidth=2))

    # AFTER MERGE (bottom section, y=0.5-3.5)
    # Commits (reposition)
    add_commit_node(ax, 3, 2, 'C1', COLORS['commit'])
    add_commit_node(ax, 5.5, 2.5, 'C2', COLORS['common_ancestor'], size=0.8)
    add_commit_node(ax, 5.5, 1.5, 'C2', COLORS['common_ancestor'], size=0.8)
    add_commit_node(ax, 8, 3, 'C3', COLORS['commit'], size=0.8)
    add_commit_node(ax, 8, 1, 'C4', COLORS['commit'], size=0.8)
    add_commit_node(ax, 10.5, 2, 'M\nMerge', COLORS['merge_commit'], size=0.9)

    # Arrows (commits point backwards)
    add_arrow(ax, 4.8, 2.4, 3.8, 2.1)  # C2 (top) -> C1
    add_arrow(ax, 4.8, 1.6, 3.8, 1.9)  # C2 (bottom) -> C1
    add_arrow(ax, 7.3, 2.9, 6.2, 2.6)  # C3 -> C2 (top)
    add_arrow(ax, 7.3, 1.1, 6.2, 1.4)  # C4 -> C2 (bottom)
    add_arrow(ax, 9.7, 2.4, 8.8, 2.8)  # M -> C3
    add_arrow(ax, 9.7, 1.6, 8.8, 1.2)  # M -> C4

    # HEAD and branch labels
    add_branch_label(ax, 12.5, 2.5, 'HEAD', COLORS['head'])
    add_branch_label(ax, 12.5, 1.5, 'main', COLORS['branch_feature'])

    # Dashed arrows
    add_arrow(ax, 12.5, 2.3, 12.5, 1.7, style='dashed', color='gray')
    add_arrow(ax, 11.7, 1.5, 11.3, 1.8, style='dashed', color='gray')

    # Explanation text
    ax.text(7, 0.5, 'Result: Git creates a new merge commit M with two parents (C3 and C4)!',
            fontsize=12, ha='center', style='italic',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#ffffcc', edgecolor='black', linewidth=1.5))

    # Source attribution
    ax.text(0.5, 0.3, 'Generated by: diagram-generators/git_three_way_merge.py',
            fontsize=9, style='italic', color='#666', transform=ax.transAxes)

    # Save
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"✓ Generated: {output_path}")

if __name__ == "__main__":
    create_diagram()
