"""
Generate Git Object Model diagram
Shows: Commit -> Tree -> Blobs hierarchy
"""

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle
import os

OUTPUT_DIR = "../figures"
os.makedirs(OUTPUT_DIR, exist_ok=True)

COLORS = {
    'commit': '#e8f5e9',
    'tree': '#fff4e1',
    'blob': '#e1f5ff',
    'meta': '#f0f0f0',
}

def create_diagram():
    fig, ax = plt.subplots(figsize=(14, 10), dpi=150)
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 10)
    ax.axis('off')

    # Helper function for boxes
    def add_box(x, y, width, height, text, color, fontsize=13):
        box = FancyBboxPatch((x, y), width, height,
                            boxstyle="round,pad=0.1",
                            facecolor=color,
                            edgecolor='black',
                            linewidth=2.5)
        ax.add_patch(box)
        ax.text(x + width/2, y + height/2, text,
                ha='center', va='center',
                fontsize=fontsize, fontweight='bold')

    def add_arrow(x1, y1, x2, y2, label=''):
        arrow = FancyArrowPatch((x1, y1), (x2, y2),
                               arrowstyle='->,head_width=0.6,head_length=0.6',
                               color='black',
                               linewidth=2,
                               mutation_scale=25)
        ax.add_patch(arrow)
        if label:
            mid_x, mid_y = (x1 + x2) / 2, (y1 + y2) / 2
            ax.text(mid_x + 0.3, mid_y, label,
                   fontsize=10, style='italic')

    # Commit (top)
    add_box(5.5, 8, 3, 0.9, 'Commit\na1b2c3', COLORS['commit'], 14)

    # Metadata boxes
    add_box(9.5, 8.5, 3, 0.6, 'Parent: null', COLORS['meta'], 11)
    add_box(9.5, 7.7, 3.8, 0.6, "Message: 'Initial commit'", COLORS['meta'], 10)

    # Arrows from commit to metadata
    add_arrow(8.5, 8.5, 9.5, 8.7)
    add_arrow(8.5, 8.2, 9.5, 8.0)

    # Main tree
    add_box(5.5, 6, 3, 0.9, 'Tree\ndef456', COLORS['tree'], 14)
    add_arrow(7, 8, 7, 6.9, 'tree')

    # Blobs and subtree (level 2)
    add_box(1, 4, 2.3, 0.8, 'Blob:\nREADME.md', COLORS['blob'], 11)
    add_box(4, 4, 2.3, 0.8, 'Blob:\nmain.py', COLORS['blob'], 11)
    add_box(7.5, 4, 2.3, 0.8, 'Tree:\nsrc/', COLORS['tree'], 11)
    add_box(11, 4, 2.3, 0.8, 'Blob:\n.gitignore', COLORS['blob'], 11)

    # Arrows from main tree to children
    add_arrow(6.2, 6, 2.15, 4.8)
    add_arrow(6.7, 6, 5.15, 4.8)
    add_arrow(7.5, 6, 8.65, 4.8)
    add_arrow(8, 6.2, 12.15, 4.8)

    # Subtree child
    add_box(7.5, 2, 2.3, 0.8, 'Blob:\nutils.py', COLORS['blob'], 11)
    add_arrow(8.65, 4, 8.65, 2.8)

    plt.title('Git Object Model', fontsize=20, fontweight='bold', pad=15)

    # Legend
    legend_y = 0.7
    add_box(0.5, legend_y, 1.5, 0.5, 'Commit', COLORS['commit'], 10)
    add_box(2.5, legend_y, 1.5, 0.5, 'Tree', COLORS['tree'], 10)
    add_box(4.5, legend_y, 1.5, 0.5, 'Blob', COLORS['blob'], 10)

    # Source attribution
    ax.text(0.5, 0.2, 'Generated by: diagram-generators/git_object_model.py',
            fontsize=9, style='italic', color='#666')

    plt.tight_layout()
    output_path = f'{OUTPUT_DIR}/git_object_model.png'
    plt.savefig(output_path, bbox_inches='tight', dpi=150, facecolor='white')
    plt.close()

    return output_path

if __name__ == "__main__":
    output = create_diagram()
    print(f"✓ Generated: {output}")
