#!/usr/bin/env python3
"""Generate complete Git workflow showing feature development with branches."""
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Circle
import os

OUTPUT_DIR, OUTPUT_FILE = "../figures", "git_complete_workflow.png"
COLORS = {'main': '#e8f5e9', 'feature': '#fff4e1', 'commit': '#e1f5ff', 'merge': '#c8e6c9'}

def add_commit(ax, x, y, label, color, size=0.75):
    circle = Circle((x, y), size, facecolor=color, edgecolor='black', linewidth=2.5, zorder=3)
    ax.add_patch(circle)
    ax.text(x, y, label, ha='center', va='center', fontsize=10, fontweight='bold', zorder=4)

def add_branch_label(ax, x, y, label, color):
    box = FancyBboxPatch((x-0.7, y-0.3), 1.4, 0.6, boxstyle="round,pad=0.1", facecolor=color, edgecolor='black', linewidth=2.5, zorder=5)
    ax.add_patch(box)
    ax.text(x, y, label, ha='center', va='center', fontsize=11, fontweight='bold', zorder=6)

def add_arrow(ax, x1, y1, x2, y2):
    arrow = FancyArrowPatch((x1,y1), (x2,y2), arrowstyle='->', mutation_scale=25, linewidth=2.5, color='black', zorder=2)
    ax.add_patch(arrow)

def create_diagram():
    fig, ax = plt.subplots(figsize=(16, 10), dpi=200)
    ax.set_xlim(0, 16); ax.set_ylim(0, 10); ax.axis('off')
    
    ax.text(8, 9.5, 'Complete Git Workflow: Feature Development', fontsize=20, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#e0e0e0', edgecolor='black', linewidth=2))
    
    # Main branch timeline (y=5)
    add_commit(ax, 2, 5, 'C1', COLORS['commit'])
    add_commit(ax, 4, 5, 'C2', COLORS['commit'])
    add_commit(ax, 9, 5, 'C5', COLORS['commit'])
    add_commit(ax, 12, 5, 'M1', COLORS['merge'])
    add_commit(ax, 14.5, 5, 'C7', COLORS['commit'])
    
    add_arrow(ax, 2.75, 5, 3.25, 5)  # C1->C2
    add_arrow(ax, 4.75, 5, 8.25, 5)  # C2->C5
    add_arrow(ax, 9.75, 5, 11.25, 5)  # C5->M1
    add_arrow(ax, 12.75, 5, 13.75, 5)  # M1->C7
    
    # Feature branch (y=7)
    add_commit(ax, 6, 7, 'C3', COLORS['commit'])
    add_commit(ax, 8, 7, 'C4', COLORS['commit'])
    add_commit(ax, 11, 7, 'C6', COLORS['commit'])
    
    add_arrow(ax, 6.75, 7, 7.25, 7)  # C3->C4
    add_arrow(ax, 8.75, 7, 10.25, 7)  # C4->C6
    
    # Branch divergence (C2 to C3)
    add_arrow(ax, 4.5, 5.5, 5.5, 6.5)
    
    # Merge convergence (C5 and C6 to M1)
    add_arrow(ax, 9.5, 5.5, 11.5, 5.5)  # C5 to M1
    add_arrow(ax, 11, 6.25, 11.5, 5.5)  # C6 to M1
    
    # Branch labels
    add_branch_label(ax, 14.5, 3.5, 'main', COLORS['main'])
    ax.plot([14.5, 14.5], [4.1, 4.7], 'k--', linewidth=2, alpha=0.5)
    
    add_branch_label(ax, 11, 8.5, 'feature-login', COLORS['feature'])
    ax.plot([11, 11], [7.75, 8.2], 'k--', linewidth=2, alpha=0.5)
    
    # Timeline labels
    ax.text(2, 3.5, '1. Start\nfrom C2', fontsize=10, ha='center', bbox=dict(boxstyle='round,pad=0.3', facecolor='#e0e0e0'))
    ax.text(6, 8.5, '2. Create\nfeature branch', fontsize=10, ha='center', bbox=dict(boxstyle='round,pad=0.3', facecolor='#fff4e1'))
    ax.text(7, 8.5, '3. Work on\nfeature', fontsize=10, ha='center', bbox=dict(boxstyle='round,pad=0.3', facecolor='#fff4e1'))
    ax.text(9, 3.5, '4. Meanwhile\nmain progresses', fontsize=10, ha='center', bbox=dict(boxstyle='round,pad=0.3', facecolor='#e8f5e9'))
    ax.text(12, 3.5, '5. Merge\nfeature→main', fontsize=10, ha='center', bbox=dict(boxstyle='round,pad=0.3', facecolor='#c8e6c9'))
    ax.text(14.5, 3.5-1, '6. Continue\non main', fontsize=10, ha='center', bbox=dict(boxstyle='round,pad=0.3', facecolor='#e8f5e9'))
    
    # Legend
    ax.text(2, 1.5, 'Commits: C1-C7', fontsize=11, bbox=dict(boxstyle='round,pad=0.3', facecolor='#e1f5ff'))
    ax.text(5, 1.5, 'Merge: M1 (2 parents)', fontsize=11, bbox=dict(boxstyle='round,pad=0.3', facecolor='#c8e6c9'))
    ax.text(9, 1.5, 'Branches diverge & converge', fontsize=11, bbox=dict(boxstyle='round,pad=0.3', facecolor='#ffffcc'))
    
    ax.text(8, 0.4, 'Typical workflow: branch → develop → merge back → continue', fontsize=13, ha='center', style='italic',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='#ffe0e0', linewidth=2))
    
    ax.text(0.5, 0.02, 'Generated by: diagram-generators/git_complete_workflow.py', fontsize=9, style='italic', color='#666', transform=ax.transAxes)
    
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=200, bbox_inches='tight', facecolor='white')
    plt.close()
    print(f"✓ Generated: {output_path}")

if __name__ == "__main__":
    create_diagram()
