#!/usr/bin/env python3
"""
Generate Git Clone and Fetch sequence diagrams.
"""

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle
import os

OUTPUT_DIR = "../figures"
OUTPUT_FILE = "git_clone_fetch_sequence.png"

def add_box(ax, x, y, width, height, text, color='#e0e0e0', fontsize=13):
    """Add a box."""
    box = FancyBboxPatch((x, y), width, height,
                        boxstyle="round,pad=0.1",
                        facecolor=color,
                        edgecolor='black',
                        linewidth=2.5)
    ax.add_patch(box)
    ax.text(x + width/2, y + height/2, text, ha='center', va='center',
            fontsize=fontsize, fontweight='bold')

def add_arrow(ax, x1, y1, x2, y2, label='', style='solid'):
    """Add an arrow with label."""
    arrow = FancyArrowPatch((x1, y1), (x2, y2),
                          arrowstyle='->',
                          mutation_scale=25,
                          linewidth=2.5,
                          color='black',
                          linestyle=style,
                          zorder=2)
    ax.add_patch(arrow)
    if label:
        mid_x = (x1 + x2) / 2
        mid_y = (y1 + y2) / 2
        ax.text(mid_x, mid_y + 0.2, label, fontsize=11, ha='center',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.9))

def draw_lifeline(ax, x, y_start, y_end):
    """Draw a vertical lifeline."""
    ax.plot([x, x], [y_start, y_end], 'k--', linewidth=2, alpha=0.5)

def create_diagram():
    fig, ax = plt.subplots(figsize=(16, 10), dpi=200)
    ax.set_xlim(0, 16)
    ax.set_ylim(0, 10)
    ax.axis('off')

    # Title
    ax.text(8, 9.5, 'Git Clone & Fetch Operations', fontsize=20, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#e0e0e0', edgecolor='black', linewidth=2))

    # === TOP: git clone ===
    ax.text(8, 8.7, 'git clone - Copy entire repository', fontsize=16, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#d0e0f0'))

    # Participants
    add_box(ax, 3, 7.8, 2, 0.6, 'Local', '#e1f5ff')
    add_box(ax, 11, 7.8, 2, 0.6, 'Remote', '#ffe1f5')

    # Lifelines
    draw_lifeline(ax, 4, 7.8, 6.2)
    draw_lifeline(ax, 12, 7.8, 6.2)

    # Clone arrow
    add_arrow(ax, 12, 7.5, 4, 7.2, 'Clone entire history')

    # Note box
    note_box = Rectangle((2.5, 6.2), 3, 1, facecolor='#ffffcc', edgecolor='#666',
                         linewidth=2, linestyle='--', zorder=1)
    ax.add_patch(note_box)
    ax.text(4, 6.7, 'Creates:\n• Local repo\n• Working directory\n• origin remote',
            fontsize=10, ha='center', va='center', style='italic')

    # Divider
    ax.plot([0.5, 15.5], [5.8, 5.8], 'k-', linewidth=2, alpha=0.3)

    # === BOTTOM: git fetch ===
    ax.text(8, 5.2, 'git fetch - Download new commits (no merge)', fontsize=16, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#f0e0d0'))

    # Participants
    add_box(ax, 3, 4.3, 2, 0.6, 'Local', '#e1f5ff')
    add_box(ax, 11, 4.3, 2, 0.6, 'Remote', '#ffe1f5')

    # Lifelines
    draw_lifeline(ax, 4, 4.3, 1.2)
    draw_lifeline(ax, 12, 4.3, 1.2)

    # Fetch request
    add_arrow(ax, 4, 4, 12, 3.8, 'Any new commits?')

    # Response
    add_arrow(ax, 12, 3.4, 4, 3.2, "Here's C4, C5", style='dashed')

    # Note box
    note_box2 = Rectangle((2.5, 1.2), 3, 1, facecolor='#ffffcc', edgecolor='#666',
                          linewidth=2, linestyle='--', zorder=1)
    ax.add_patch(note_box2)
    ax.text(4, 1.7, 'Updates:\n• origin/main\nLocal main\nunchanged',
            fontsize=10, ha='center', va='center', style='italic')

    # Key difference
    ax.text(8, 0.4, 'Key: fetch downloads but doesn\'t modify your working directory or current branch',
            fontsize=13, ha='center', fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='#ffe0e0', linewidth=2.5))

    # Source attribution
    ax.text(0.5, 0.02, 'Generated by: diagram-generators/git_clone_fetch_sequence.py',
            fontsize=9, style='italic', color='#666', transform=ax.transAxes)

    # Save
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=200, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"✓ Generated: {output_path}")

if __name__ == "__main__":
    create_diagram()
