#!/usr/bin/env python3
"""
Generate diagram showing commits on a feature branch.
Shows how feature branch moves forward while main stays at C2.
"""

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Circle
import os

OUTPUT_DIR = "../figures"
OUTPUT_FILE = "git_branch_commit.png"

COLORS = {
    'head': '#ffe1f5',
    'branch_main': '#fff4e1',
    'branch_feature': '#e8f5e9',
    'commit': '#e1f5ff',
    'new_commit': '#c8e6c9',
}

def add_commit_node(ax, x, y, label, color, size=0.8):
    """Add a commit node (circle)."""
    circle = Circle((x, y), size, facecolor=color, edgecolor='black', linewidth=2.5, zorder=3)
    ax.add_patch(circle)
    # Handle multi-line labels
    ax.text(x, y, label, ha='center', va='center', fontsize=11, fontweight='bold', zorder=4)

def add_branch_label(ax, x, y, label, color):
    """Add a branch label box."""
    box = FancyBboxPatch((x - 0.8, y - 0.35), 1.6, 0.7,
                        boxstyle="round,pad=0.1",
                        facecolor=color,
                        edgecolor='black',
                        linewidth=2.5,
                        zorder=5)
    ax.add_patch(box)
    ax.text(x, y, label, ha='center', va='center', fontsize=13, fontweight='bold', zorder=6)

def add_arrow(ax, x1, y1, x2, y2, style='solid', color='black'):
    """Add an arrow."""
    arrow = FancyArrowPatch((x1, y1), (x2, y2),
                          arrowstyle='->',
                          mutation_scale=28,
                          linewidth=2.5,
                          color=color,
                          linestyle=style,
                          zorder=2)
    ax.add_patch(arrow)

def create_diagram():
    fig, ax = plt.subplots(figsize=(16, 8), dpi=200)
    ax.set_xlim(0, 16)
    ax.set_ylim(0, 8)
    ax.axis('off')

    # Title
    ax.text(8, 7.3, 'Making Commits on a Feature Branch', fontsize=20, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#e0e0e0', edgecolor='black', linewidth=2))

    ax.text(8, 6.5, 'After: git commit -m "Add API integration" (on feature branch)', fontsize=15,
            ha='center', style='italic',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#f0f0e0'))

    # Commits (right to left for history)
    add_commit_node(ax, 3, 4, 'C1:\nAdd\nmodel', COLORS['commit'])
    add_commit_node(ax, 6, 4, 'C2:\nAdd\ntests', COLORS['commit'])
    add_commit_node(ax, 9, 4, 'C3:\nAdd\nAPI', COLORS['new_commit'])

    # Arrows (commits point backwards)
    add_arrow(ax, 5.2, 4, 3.8, 4)  # C2 -> C1
    add_arrow(ax, 8.2, 4, 6.8, 4)  # C3 -> C2

    # Branch labels
    add_branch_label(ax, 12, 5, 'feature', COLORS['branch_feature'])
    add_arrow(ax, 11.2, 4.7, 9.8, 4.2, style='dashed', color='gray')

    add_branch_label(ax, 12, 3, 'main', COLORS['branch_main'])
    add_arrow(ax, 11.2, 3.3, 6.8, 3.8, style='dashed', color='gray')

    # HEAD points to feature
    add_branch_label(ax, 14.5, 5, 'HEAD', COLORS['head'])
    add_arrow(ax, 13.7, 5, 12.8, 5, style='dashed', color='gray')

    # Annotations
    ax.text(9, 2, 'New commit C3\n(green highlight)', fontsize=12, ha='center',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#c8e6c9', linewidth=2))

    ax.text(6, 1, 'main branch\nunchanged at C2', fontsize=12, ha='center',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#fff4e1', linewidth=2))

    # Key observation
    ax.text(8, 0.3, 'Key: feature moved forward to C3, main still at C2 → branches have diverged!',
            fontsize=13, ha='center', fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='#ffe0e0', linewidth=2.5))

    # Source attribution
    ax.text(0.5, 0.02, 'Generated by: diagram-generators/git_branch_commit.py',
            fontsize=9, style='italic', color='#666', transform=ax.transAxes)

    # Save
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=200, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"✓ Generated: {output_path}")

if __name__ == "__main__":
    create_diagram()
