#!/usr/bin/env python3
"""Generate Git Collaboration Workflow sequence diagram."""
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import os

OUTPUT_DIR, OUTPUT_FILE = "../figures", "git_collaboration_workflow.png"

def add_box(ax, x, y, w, h, text, color='#e0e0e0', fs=11):
    box = FancyBboxPatch((x,y), w, h, boxstyle="round,pad=0.08", facecolor=color, edgecolor='black', linewidth=2)
    ax.add_patch(box)
    lines = text.split('\n')
    y_offset = h/2 + (len(lines)-1)*0.15
    for line in lines:
        ax.text(x+w/2, y+y_offset, line, ha='center', va='center', fontsize=fs, fontweight='bold' if fs>10 else 'normal')
        y_offset -= 0.3

def add_arrow(ax, x1, y1, x2, y2, label=''):
    arrow = FancyArrowPatch((x1,y1), (x2,y2), arrowstyle='->', mutation_scale=15, linewidth=1.5, color='black', zorder=2)
    ax.add_patch(arrow)
    if label:
        mid_x = (x1+x2)/2
        ax.text(mid_x+0.1, y1, label, fontsize=9, ha='left', bbox=dict(boxstyle='round,pad=0.15', facecolor='white', alpha=0.9))

def draw_lifeline(ax, x, y_start, y_end):
    ax.plot([x, x], [y_start, y_end], 'k--', linewidth=1.5, alpha=0.5)

def create_diagram():
    fig, ax = plt.subplots(figsize=(16, 13), dpi=200)
    ax.set_xlim(0, 16); ax.set_ylim(0, 13); ax.axis('off')
    
    ax.text(8, 12.5, 'Git Collaboration Workflow (Pull Request)', fontsize=20, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.6', facecolor='#e0e0e0', edgecolor='black', linewidth=2))
    
    # Participants
    add_box(ax, 0.5, 11.5, 2.2, 0.6, 'Alice\n(Developer)', '#e1f5ff', 11)
    add_box(ax, 3.5, 11.5, 2.2, 0.6, "Alice's\nLocal", '#d0e0f0', 11)
    add_box(ax, 6.8, 11.5, 2.4, 0.6, 'GitHub\n(Remote)', '#ffe1f5', 11)
    add_box(ax, 10.2, 11.5, 2.2, 0.6, "Bob's\nLocal", '#d0e0f0', 11)
    add_box(ax, 13.2, 11.5, 2.2, 0.6, 'Bob\n(Reviewer)', '#e8f5e9', 11)
    
    # Lifelines
    for x in [1.6, 4.6, 8, 11.3, 14.3]:
        draw_lifeline(ax, x, 11.5, 0.8)
    
    y = 11
    
    # Development phase
    add_arrow(ax, 1.6, y, 4.6, y, 'checkout -b feature'); y -= 0.5
    add_arrow(ax, 1.6, y, 4.6, y, 'Make changes'); y -= 0.5
    add_arrow(ax, 1.6, y, 4.6, y, 'commit'); y -= 0.5
    add_arrow(ax, 4.6, y, 8, y, 'push origin feature'); y -= 0.6
    
    # PR creation
    add_arrow(ax, 1.6, y, 8, y, 'Create Pull Request'); y -= 0.5
    add_arrow(ax, 8, y, 14.3, y, 'Email notification'); y -= 0.6
    
    # Review phase  
    add_box(ax, 12, y-0.3, 3, 0.5, 'REVIEW PHASE', '#ffffcc', 10)
    y -= 0.8
    add_arrow(ax, 14.3, y, 8, y, 'Review code'); y -= 0.5
    add_arrow(ax, 14.3, y, 8, y, 'Request changes'); y -= 0.6
    
    # Fix phase
    add_arrow(ax, 1.6, y, 4.6, y, 'Fix issues'); y -= 0.5
    add_arrow(ax, 4.6, y, 8, y, 'push (updates PR)'); y -= 0.6
    
    # Approval
    add_arrow(ax, 14.3, y, 8, y, 'Approve PR'); y -= 0.5
    add_box(ax, 6.8, y-0.4, 2.4, 0.5, 'Merge\nfeature→main', '#ccffcc', 10)
    y -= 0.8
    
    # Sync
    add_arrow(ax, 1.6, y, 4.6, y, 'checkout main'); y -= 0.5
    add_arrow(ax, 4.6, y, 8, y, 'pull'); y -= 0.5
    add_arrow(ax, 11.3, y, 8, y, 'pull'); y -= 0.6
    
    ax.text(8, 0.4, 'Collaborative workflow: feature branch → review → merge → sync', fontsize=12, ha='center', style='italic',
            bbox=dict(boxstyle='round,pad=0.4', facecolor='#e0ffe0', linewidth=2))
    
    ax.text(0.5, 0.02, 'Generated by: diagram-generators/git_collaboration_workflow.py', fontsize=9, style='italic', color='#666', transform=ax.transAxes)
    
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=200, bbox_inches='tight', facecolor='white')
    plt.close()
    print(f"✓ Generated: {output_path}")

if __name__ == "__main__":
    create_diagram()
