#!/usr/bin/env python3
"""
Generate LLM Sampling Strategies comparison diagram.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import os

# Output configuration
OUTPUT_DIR = "../figures"
OUTPUT_FILE = "llm_sampling_strategies.png"

# Color scheme
COLORS = {
    'greedy': '#e1f5ff',
    'temperature': '#fff4e1',
    'top_p': '#ffe1f5',
    'top_k': '#e8f5e9',
}

def add_box(ax, x, y, width, height, text, color, fontsize=13):
    """Add a rounded box with text."""
    box = FancyBboxPatch((x, y), width, height,
                        boxstyle="round,pad=0.15",
                        facecolor=color,
                        edgecolor='black',
                        linewidth=2.5)
    ax.add_patch(box)
    # Split text for better wrapping
    ax.text(x + width/2, y + height/2, text, ha='center', va='center',
            fontsize=fontsize, fontweight='bold')

def add_arrow(ax, x1, y1, x2, y2, label='', style='solid'):
    """Add an arrow with optional label."""
    arrow = FancyArrowPatch((x1, y1), (x2, y2),
                          arrowstyle='->,head_width=0.4,head_length=0.6',
                          mutation_scale=25,
                          linewidth=2.5,
                          color='black',
                          linestyle=style,
                          zorder=2)
    ax.add_patch(arrow)

    if label:
        # Position label at midpoint
        mid_x = (x1 + x2) / 2
        mid_y = (y1 + y2) / 2
        ax.text(mid_x + 0.3, mid_y, label, fontsize=10, style='italic',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='none', alpha=0.8))

def create_diagram():
    fig, ax = plt.subplots(figsize=(14, 9), dpi=150)
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 9)
    ax.axis('off')

    # Title
    ax.text(7, 8.3, 'Comparing Sampling Strategies', fontsize=18, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='#e0e0e0', edgecolor='black', linewidth=2))

    # Top level: Original Distribution
    add_box(ax, 5.5, 7, 3, 0.8, 'Original\nDistribution', '#d0d0d0', fontsize=14)

    # Second level: Sampling Method decision
    add_box(ax, 5.5, 5.5, 3, 0.8, 'Sampling Method', '#b0b0b0', fontsize=14)

    # Arrow from Original to Sampling Method
    add_arrow(ax, 7, 7, 7, 6.3)

    # Third level: Four sampling strategies
    strategies = [
        (1, 'Greedy\nT=0', COLORS['greedy']),
        (4, 'Temperature', COLORS['temperature']),
        (7, 'Top-P', COLORS['top_p']),
        (10, 'Top-K', COLORS['top_k'])
    ]

    for x, label, color in strategies:
        add_box(ax, x - 0.9, 4, 1.8, 0.8, label, color)
        # Arrow from Sampling Method to strategy
        add_arrow(ax, 7, 5.5, x, 4.8)

    # Fourth level: Characteristics
    characteristics = [
        (1, 'Always pick\nmax', 'Deterministic', COLORS['greedy']),
        (4, 'Reshape\ndistribution', 'Random but\ncontrolled', COLORS['temperature']),
        (7, 'Truncate\ntail', 'Adaptive\ncutoff', COLORS['top_p']),
        (10, 'Keep top K\ntokens', 'Fixed\ncutoff', COLORS['top_k'])
    ]

    for x, method_text, result_text, color in characteristics:
        # Method box
        add_box(ax, x - 0.9, 2.5, 1.8, 0.8, method_text, color, fontsize=11)
        add_arrow(ax, x, 4, x, 3.3)

        # Result box
        add_box(ax, x - 0.9, 1, 1.8, 0.8, result_text, color, fontsize=11)
        add_arrow(ax, x, 2.5, x, 1.8)

    # Add explanatory notes at bottom
    notes = [
        "Greedy: Most predictable, repetitive",
        "Temperature: Controls randomness",
        "Top-P (nucleus): Dynamic vocabulary",
        "Top-K: Fixed vocabulary size"
    ]

    for i, note in enumerate(notes):
        x_pos = 1 + i * 3.25
        ax.text(x_pos, 0.3, note, fontsize=9, ha='left', style='italic',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='#ffffed', edgecolor='gray', linewidth=1))

    # Source attribution
    ax.text(0.5, 0.02, 'Generated by: diagram-generators/llm_sampling_strategies.py',
            fontsize=9, style='italic', color='#666', transform=ax.transAxes)

    # Save
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"✓ Generated: {output_path}")

if __name__ == "__main__":
    create_diagram()
