#!/usr/bin/env python3
"""
Generate LLM Pipeline diagram showing the flow from input text to output token.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import os

# Output configuration
OUTPUT_DIR = "../figures"
OUTPUT_FILE = "llm_pipeline.png"

# Color scheme
COLORS = {
    'input': '#e1f5ff',
    'processing': '#fff4e1',
    'probability': '#ffe1f5',
    'output': '#e8f5e9',
}

def add_box(ax, x, y, width, height, text, color, fontsize=14):
    """Add a rounded box with text."""
    box = FancyBboxPatch((x, y), width, height,
                        boxstyle="round,pad=0.15",
                        facecolor=color,
                        edgecolor='black',
                        linewidth=2.5)
    ax.add_patch(box)
    ax.text(x + width/2, y + height/2, text, ha='center', va='center',
            fontsize=fontsize, fontweight='bold', wrap=True)

def add_arrow(ax, x1, y1, x2, y2):
    """Add an arrow between boxes."""
    arrow = FancyArrowPatch((x1, y1), (x2, y2),
                          arrowstyle='->,head_width=0.6,head_length=0.8',
                          mutation_scale=30,
                          linewidth=3,
                          color='black',
                          zorder=2)
    ax.add_patch(arrow)

def create_diagram():
    fig, ax = plt.subplots(figsize=(16, 5), dpi=150)
    ax.set_xlim(0, 16)
    ax.set_ylim(0, 5)
    ax.axis('off')

    # Box dimensions
    box_width = 1.8
    box_height = 1.2
    y_center = 2.5
    y_box = y_center - box_height/2

    # Spacing between boxes
    spacing = 0.6

    # Calculate positions
    positions = []
    x_start = 0.5
    for i in range(7):
        x = x_start + i * (box_width + spacing)
        positions.append(x)

    # Draw boxes
    add_box(ax, positions[0], y_box, box_width, box_height,
            'Input\nText', COLORS['input'])
    add_box(ax, positions[1], y_box, box_width, box_height,
            'Tokenization', COLORS['input'])
    add_box(ax, positions[2], y_box, box_width, box_height,
            'Embeddings', COLORS['input'])
    add_box(ax, positions[3], y_box, box_width, box_height,
            'Transformer\nLayers', COLORS['processing'])
    add_box(ax, positions[4], y_box, box_width, box_height,
            'Probability\nDistribution', COLORS['probability'])
    add_box(ax, positions[5], y_box, box_width, box_height,
            'Sample\nNext Token', COLORS['output'])
    add_box(ax, positions[6], y_box, box_width, box_height,
            'Repeat', COLORS['output'])

    # Draw arrows
    for i in range(6):
        x1 = positions[i] + box_width
        x2 = positions[i+1]
        add_arrow(ax, x1, y_center, x2, y_center)

    # Add curved arrow from Repeat back to the beginning
    from matplotlib.patches import FancyArrowPatch
    import matplotlib.patches as mpatches

    # Curved feedback arrow
    feedback_arrow = FancyArrowPatch(
        (positions[6] + box_width/2, y_box - 0.1),
        (positions[3] + box_width/2, y_box - 0.1),
        arrowstyle='->,head_width=0.6,head_length=0.8',
        mutation_scale=30,
        linewidth=2.5,
        color='#666',
        linestyle='dashed',
        connectionstyle="arc3,rad=-.5",
        zorder=1
    )
    ax.add_patch(feedback_arrow)

    ax.text(7.5, 0.6, 'Autoregressive generation loop',
            ha='center', fontsize=11, style='italic', color='#666')

    # Title
    ax.text(8, 4.3, 'LLM Generation Pipeline', fontsize=18, fontweight='bold', ha='center',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='#f0f0f0', edgecolor='black', linewidth=2))

    # Source attribution
    ax.text(0.5, 0.05, 'Generated by: diagram-generators/llm_pipeline.py',
            fontsize=9, style='italic', color='#666', transform=ax.transAxes)

    # Save
    output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILE)
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close()

    print(f"✓ Generated: {output_path}")

if __name__ == "__main__":
    create_diagram()
